### PR TITLE
Let users decide the number of threads

### PR DESCRIPTION
**Pull request by SubhrajyotiSen**

### CODE REVIEW

**Comment by akhilnarang** [comment]
I say better change it to mka

**Comment by tywinlannister7** [comment]
@SubhrajyotiSen Yep, good choice.

**Comment by SubhrajyotiSen** [comment]
@akhilnarang So should I change it to 'mka ownrom' now?

**Comment by MZO9400** [comment]
-j$(nproc --all) >> all

**Comment by akhilnarang** [comment]
mka will do that :3

**Pull request merged**
